version: "3"
services:
  zoo:
    image: bitnami/zookeeper:3
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zoo

  db:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000

  app:
    build: .
    volumes:
      - .:/app/rust-cqrses-bankaccount
    working_dir: /app/rust-cqrses-bankaccount
    user: "${UID}:${GID}"
    environment:
      AWS_ACCESS_KEY_ID: LOCAL
      AWS_SECRET_ACCESS_KEY: LOCAL
      AWS_DEFAULT_REGION: ap-northeast-1
    tty: true
    links:
      - kafka
      - db
