version: "3"
services:
  zoo:
    image: bitnami/zookeeper:3
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zoo

  event_store:
    image: mariadb:10.4
    ports:
      - 3306:3306
    environment:
      LANG: ja_JP.UTF-8
      MYSQL_DATABASE: event_store_db
      MYSQL_ROOT_PASSWORD: pass
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    tty: true
    restart: always

  app:
    build: .
    volumes:
      - .:/app/rust-cqrses-bankaccount
    working_dir: /app/rust-cqrses-bankaccount
    user: "${UID}:${GID}"
    env_file: .env
    tty: true
    links:
      - kafka
      - event_store
